spring:
  application:
    name: back
server:
  port: ${SERVER_PORT}
  address: ${SERVER_ADDRESS}

logging:
  file:
    name: logs/back.log
  logback:
    rollingpolicy:
      file-name-pattern: logs/back-%d{yyyy-MM-dd}.%i.log

cors:
  allowed-origins: ${ALLOWED_ORIGINS}