spring:
  datasource:
    url: ${DB_DEV_URL}
    username: ${DB_DEV_USR}
    password: ${DB_DEV_PWD}
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  data:
    redis:
      host: ${REDIS_DEV_HOST}
      port: 6379
      username: ${REDIS_DEV_USR}
      password: ${REDIS_DEV_PWD}
      ssl:
        enabled: false


logging:
  level:
    dev:
      jos:
        back: DEBUG
